name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths-ignore: /log/**

jobs:
  Delivery-S3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-code
        uses: actions/checkout@v3

      - name: Build Docker and Copy files
        run: |
          docker build -t delivery-app .
          docker run --name copy-this delivery-app
          docker cp copy-this:/copy ./dist

      - name: Configuration AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-northeast-2"

      - name: To AWS S3
        run: |
          aws s3 sync ./dist s3://actiontos3 --delete
