name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths-ignore: /log/**

jobs:
  Delivery-S3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-code
        uses: actions/checkout@v4

      - name: Build Docker and Copy files
        run: |
          docker build -t delivery-app
          docker run --name copy-this delivery-app
          docker cp copy-this:/copy ./dist

      - name: To AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS.ACCESS_KEY_SECRET }}
          AWS_REGION: "ap-northeast-2"
        run: |
          aws s3 sync ./dist s3://actiontos3 --delete
