name: Logging commit summary

on:
  push:
    branches:
      - main
    paths-ignore: /log/**

jobs:
  recording-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-code
        uses: actions/checkout@v4

      - name: Setup-Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Running-logger
        run: node .github/workflows/commit-logger.js

      - name: Log-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "Workflow"
          git config --local user.email "kwakyh951@gmail.com"
          git add log/commit/commit-log.txt
          git commit -m "saved commit logs"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/KwakYounHo/GitHub-action-first.git
